-- ====================================================================
-- SRI LAKSHMI TEX — Migration 003: 48 Commercial Palette Colors
-- For Leggings, Palazzo Pants, Patiala Pants, and Shimmer Ankle Leggings
-- ====================================================================

-- 1. Remove previous/placeholder colors for the 4 bottom wear products
DELETE FROM product_colors WHERE product_id IN ('prod-leggings', 'prod-palazzo', 'prod-patiala', 'prod-shimmer');

-- 2. Insert verified 48 colors for each of the 4 bottom wear products
INSERT INTO product_colors (id, product_id, color_name, color_code, image_url)
VALUES
  ('prod-leggings-c-001', 'prod-leggings', '001 | Golden Yellow', '#F5A623', '/products/leggings.jpg'),
  ('prod-leggings-c-002', 'prod-leggings', '002 | Navy', '#1C4465', '/products/leggings.jpg'),
  ('prod-leggings-c-003', 'prod-leggings', '003 | Red', '#D91A2A', '/products/leggings.jpg'),
  ('prod-leggings-c-004', 'prod-leggings', '004 | Mustard', '#C68A20', '/products/leggings.jpg'),
  ('prod-leggings-c-005', 'prod-leggings', '005 | Black', '#232323', '/products/leggings.jpg'),
  ('prod-leggings-c-006', 'prod-leggings', '006 | P. Green', '#0A8B47', '/products/leggings.jpg'),
  ('prod-leggings-c-007', 'prod-leggings', '007 | Ink Blue', '#1754A8', '/products/leggings.jpg'),
  ('prod-leggings-c-008', 'prod-leggings', '008 | Baby Pink', '#F4A7C1', '/products/leggings.jpg'),
  ('prod-leggings-c-009', 'prod-leggings', '009 | Pink', '#E33582', '/products/leggings.jpg'),
  ('prod-leggings-c-010', 'prod-leggings', '010 | Magenta', '#BF1B75', '/products/leggings.jpg'),
  ('prod-leggings-c-011', 'prod-leggings', '011 | Purple', '#5C2B79', '/products/leggings.jpg'),
  ('prod-leggings-c-012', 'prod-leggings', '012 | White', '#FFFFFF', '/products/leggings.jpg'),
  ('prod-leggings-c-013', 'prod-leggings', '013 | Lemon Yellow', '#FFC82B', '/products/leggings.jpg'),
  ('prod-leggings-c-014', 'prod-leggings', '014 | Reliance Green', '#008D9B', '/products/leggings.jpg'),
  ('prod-leggings-c-015', 'prod-leggings', '015 | L. Skin', '#E3C5A8', '/products/leggings.jpg'),
  ('prod-leggings-c-016', 'prod-leggings', '016 | Bottle Green', '#1A543E', '/products/leggings.jpg'),
  ('prod-leggings-c-017', 'prod-leggings', '017 | Maroon', '#6B2438', '/products/leggings.jpg'),
  ('prod-leggings-c-018', 'prod-leggings', '018 | Mehandi', '#96A329', '/products/leggings.jpg'),
  ('prod-leggings-c-019', 'prod-leggings', '019 | D. Purple', '#462A5E', '/products/leggings.jpg'),
  ('prod-leggings-c-020', 'prod-leggings', '020 | Sky Blue', '#0595C8', '/products/leggings.jpg'),
  ('prod-leggings-c-021', 'prod-leggings', '021 | Coffee', '#6E4437', '/products/leggings.jpg'),
  ('prod-leggings-c-022', 'prod-leggings', '022 | Peacock', '#006E82', '/products/leggings.jpg'),
  ('prod-leggings-c-023', 'prod-leggings', '023 | Honey', '#C84831', '/products/leggings.jpg'),
  ('prod-leggings-c-024', 'prod-leggings', '024 | Olive', '#4A6E3B', '/products/leggings.jpg'),
  ('prod-leggings-c-025', 'prod-leggings', '025 | Orange', '#F25A1E', '/products/leggings.jpg'),
  ('prod-leggings-c-026', 'prod-leggings', '026 | F-Rose', '#DE3D56', '/products/leggings.jpg'),
  ('prod-leggings-c-027', 'prod-leggings', '027 | Half White', '#F8F5E4', '/products/leggings.jpg'),
  ('prod-leggings-c-028', 'prod-leggings', '028 | D. Skin', '#B38354', '/products/leggings.jpg'),
  ('prod-leggings-c-029', 'prod-leggings', '029 | D. Milange', '#54372D', '/products/leggings.jpg'),
  ('prod-leggings-c-030', 'prod-leggings', '030 | Parrot', '#42C727', '/products/leggings.jpg'),
  ('prod-leggings-c-031', 'prod-leggings', '031 | Jerry Red', '#D31434', '/products/leggings.jpg'),
  ('prod-leggings-c-032', 'prod-leggings', '032 | L. Grey', '#82929E', '/products/leggings.jpg'),
  ('prod-leggings-c-033', 'prod-leggings', '033 | Jute', '#B0A08D', '/products/leggings.jpg'),
  ('prod-leggings-c-034', 'prod-leggings', '034 | D. Grey', '#47545D', '/products/leggings.jpg'),
  ('prod-leggings-c-035', 'prod-leggings', '035 | Yellow', '#EDB91A', '/products/leggings.jpg'),
  ('prod-leggings-c-036', 'prod-leggings', '036 | Stone', '#D6B495', '/products/leggings.jpg'),
  ('prod-leggings-c-037', 'prod-leggings', '037 | Red Maroon', '#9B1D28', '/products/leggings.jpg'),
  ('prod-leggings-c-038', 'prod-leggings', '038 | Royal Blue', '#194CB0', '/products/leggings.jpg'),
  ('prod-leggings-c-039', 'prod-leggings', '039 | Grape', '#843E5E', '/products/leggings.jpg'),
  ('prod-leggings-c-040', 'prod-leggings', '040 | Red Orange', '#E8291F', '/products/leggings.jpg'),
  ('prod-leggings-c-041', 'prod-leggings', '041 | Pistar', '#1FB36C', '/products/leggings.jpg'),
  ('prod-leggings-c-042', 'prod-leggings', '042 | Lrz Green', '#0D7B6C', '/products/leggings.jpg'),
  ('prod-leggings-c-043', 'prod-leggings', '043 | Wine', '#672B3D', '/products/leggings.jpg'),
  ('prod-leggings-c-044', 'prod-leggings', '044 | D. Pink', '#D9256E', '/products/leggings.jpg'),
  ('prod-leggings-c-045', 'prod-leggings', '045 | Light Blue', '#95CCE5', '/products/leggings.jpg'),
  ('prod-leggings-c-046', 'prod-leggings', '046 | Peach', '#EB7866', '/products/leggings.jpg'),
  ('prod-leggings-c-047', 'prod-leggings', '047 | White', '#F3F4F6', '/products/leggings.jpg'),
  ('prod-leggings-c-048', 'prod-leggings', '048 | Beige', '#DFD0BD', '/products/leggings.jpg'),
  ('prod-palazzo-c-001', 'prod-palazzo', '001 | Golden Yellow', '#F5A623', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-002', 'prod-palazzo', '002 | Navy', '#1C4465', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-003', 'prod-palazzo', '003 | Red', '#D91A2A', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-004', 'prod-palazzo', '004 | Mustard', '#C68A20', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-005', 'prod-palazzo', '005 | Black', '#232323', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-006', 'prod-palazzo', '006 | P. Green', '#0A8B47', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-007', 'prod-palazzo', '007 | Ink Blue', '#1754A8', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-008', 'prod-palazzo', '008 | Baby Pink', '#F4A7C1', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-009', 'prod-palazzo', '009 | Pink', '#E33582', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-010', 'prod-palazzo', '010 | Magenta', '#BF1B75', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-011', 'prod-palazzo', '011 | Purple', '#5C2B79', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-012', 'prod-palazzo', '012 | White', '#FFFFFF', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-013', 'prod-palazzo', '013 | Lemon Yellow', '#FFC82B', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-014', 'prod-palazzo', '014 | Reliance Green', '#008D9B', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-015', 'prod-palazzo', '015 | L. Skin', '#E3C5A8', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-016', 'prod-palazzo', '016 | Bottle Green', '#1A543E', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-017', 'prod-palazzo', '017 | Maroon', '#6B2438', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-018', 'prod-palazzo', '018 | Mehandi', '#96A329', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-019', 'prod-palazzo', '019 | D. Purple', '#462A5E', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-020', 'prod-palazzo', '020 | Sky Blue', '#0595C8', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-021', 'prod-palazzo', '021 | Coffee', '#6E4437', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-022', 'prod-palazzo', '022 | Peacock', '#006E82', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-023', 'prod-palazzo', '023 | Honey', '#C84831', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-024', 'prod-palazzo', '024 | Olive', '#4A6E3B', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-025', 'prod-palazzo', '025 | Orange', '#F25A1E', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-026', 'prod-palazzo', '026 | F-Rose', '#DE3D56', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-027', 'prod-palazzo', '027 | Half White', '#F8F5E4', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-028', 'prod-palazzo', '028 | D. Skin', '#B38354', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-029', 'prod-palazzo', '029 | D. Milange', '#54372D', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-030', 'prod-palazzo', '030 | Parrot', '#42C727', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-031', 'prod-palazzo', '031 | Jerry Red', '#D31434', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-032', 'prod-palazzo', '032 | L. Grey', '#82929E', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-033', 'prod-palazzo', '033 | Jute', '#B0A08D', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-034', 'prod-palazzo', '034 | D. Grey', '#47545D', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-035', 'prod-palazzo', '035 | Yellow', '#EDB91A', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-036', 'prod-palazzo', '036 | Stone', '#D6B495', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-037', 'prod-palazzo', '037 | Red Maroon', '#9B1D28', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-038', 'prod-palazzo', '038 | Royal Blue', '#194CB0', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-039', 'prod-palazzo', '039 | Grape', '#843E5E', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-040', 'prod-palazzo', '040 | Red Orange', '#E8291F', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-041', 'prod-palazzo', '041 | Pistar', '#1FB36C', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-042', 'prod-palazzo', '042 | Lrz Green', '#0D7B6C', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-043', 'prod-palazzo', '043 | Wine', '#672B3D', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-044', 'prod-palazzo', '044 | D. Pink', '#D9256E', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-045', 'prod-palazzo', '045 | Light Blue', '#95CCE5', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-046', 'prod-palazzo', '046 | Peach', '#EB7866', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-047', 'prod-palazzo', '047 | White', '#F3F4F6', '/products/palazzo-pants.jpg'),
  ('prod-palazzo-c-048', 'prod-palazzo', '048 | Beige', '#DFD0BD', '/products/palazzo-pants.jpg'),
  ('prod-patiala-c-001', 'prod-patiala', '001 | Golden Yellow', '#F5A623', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-002', 'prod-patiala', '002 | Navy', '#1C4465', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-003', 'prod-patiala', '003 | Red', '#D91A2A', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-004', 'prod-patiala', '004 | Mustard', '#C68A20', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-005', 'prod-patiala', '005 | Black', '#232323', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-006', 'prod-patiala', '006 | P. Green', '#0A8B47', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-007', 'prod-patiala', '007 | Ink Blue', '#1754A8', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-008', 'prod-patiala', '008 | Baby Pink', '#F4A7C1', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-009', 'prod-patiala', '009 | Pink', '#E33582', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-010', 'prod-patiala', '010 | Magenta', '#BF1B75', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-011', 'prod-patiala', '011 | Purple', '#5C2B79', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-012', 'prod-patiala', '012 | White', '#FFFFFF', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-013', 'prod-patiala', '013 | Lemon Yellow', '#FFC82B', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-014', 'prod-patiala', '014 | Reliance Green', '#008D9B', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-015', 'prod-patiala', '015 | L. Skin', '#E3C5A8', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-016', 'prod-patiala', '016 | Bottle Green', '#1A543E', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-017', 'prod-patiala', '017 | Maroon', '#6B2438', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-018', 'prod-patiala', '018 | Mehandi', '#96A329', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-019', 'prod-patiala', '019 | D. Purple', '#462A5E', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-020', 'prod-patiala', '020 | Sky Blue', '#0595C8', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-021', 'prod-patiala', '021 | Coffee', '#6E4437', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-022', 'prod-patiala', '022 | Peacock', '#006E82', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-023', 'prod-patiala', '023 | Honey', '#C84831', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-024', 'prod-patiala', '024 | Olive', '#4A6E3B', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-025', 'prod-patiala', '025 | Orange', '#F25A1E', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-026', 'prod-patiala', '026 | F-Rose', '#DE3D56', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-027', 'prod-patiala', '027 | Half White', '#F8F5E4', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-028', 'prod-patiala', '028 | D. Skin', '#B38354', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-029', 'prod-patiala', '029 | D. Milange', '#54372D', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-030', 'prod-patiala', '030 | Parrot', '#42C727', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-031', 'prod-patiala', '031 | Jerry Red', '#D31434', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-032', 'prod-patiala', '032 | L. Grey', '#82929E', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-033', 'prod-patiala', '033 | Jute', '#B0A08D', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-034', 'prod-patiala', '034 | D. Grey', '#47545D', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-035', 'prod-patiala', '035 | Yellow', '#EDB91A', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-036', 'prod-patiala', '036 | Stone', '#D6B495', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-037', 'prod-patiala', '037 | Red Maroon', '#9B1D28', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-038', 'prod-patiala', '038 | Royal Blue', '#194CB0', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-039', 'prod-patiala', '039 | Grape', '#843E5E', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-040', 'prod-patiala', '040 | Red Orange', '#E8291F', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-041', 'prod-patiala', '041 | Pistar', '#1FB36C', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-042', 'prod-patiala', '042 | Lrz Green', '#0D7B6C', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-043', 'prod-patiala', '043 | Wine', '#672B3D', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-044', 'prod-patiala', '044 | D. Pink', '#D9256E', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-045', 'prod-patiala', '045 | Light Blue', '#95CCE5', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-046', 'prod-patiala', '046 | Peach', '#EB7866', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-047', 'prod-patiala', '047 | White', '#F3F4F6', '/products/patiala-pants.jpg'),
  ('prod-patiala-c-048', 'prod-patiala', '048 | Beige', '#DFD0BD', '/products/patiala-pants.jpg'),
  ('prod-shimmer-c-001', 'prod-shimmer', '001 | Golden Yellow', '#F5A623', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-002', 'prod-shimmer', '002 | Navy', '#1C4465', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-003', 'prod-shimmer', '003 | Red', '#D91A2A', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-004', 'prod-shimmer', '004 | Mustard', '#C68A20', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-005', 'prod-shimmer', '005 | Black', '#232323', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-006', 'prod-shimmer', '006 | P. Green', '#0A8B47', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-007', 'prod-shimmer', '007 | Ink Blue', '#1754A8', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-008', 'prod-shimmer', '008 | Baby Pink', '#F4A7C1', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-009', 'prod-shimmer', '009 | Pink', '#E33582', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-010', 'prod-shimmer', '010 | Magenta', '#BF1B75', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-011', 'prod-shimmer', '011 | Purple', '#5C2B79', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-012', 'prod-shimmer', '012 | White', '#FFFFFF', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-013', 'prod-shimmer', '013 | Lemon Yellow', '#FFC82B', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-014', 'prod-shimmer', '014 | Reliance Green', '#008D9B', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-015', 'prod-shimmer', '015 | L. Skin', '#E3C5A8', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-016', 'prod-shimmer', '016 | Bottle Green', '#1A543E', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-017', 'prod-shimmer', '017 | Maroon', '#6B2438', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-018', 'prod-shimmer', '018 | Mehandi', '#96A329', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-019', 'prod-shimmer', '019 | D. Purple', '#462A5E', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-020', 'prod-shimmer', '020 | Sky Blue', '#0595C8', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-021', 'prod-shimmer', '021 | Coffee', '#6E4437', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-022', 'prod-shimmer', '022 | Peacock', '#006E82', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-023', 'prod-shimmer', '023 | Honey', '#C84831', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-024', 'prod-shimmer', '024 | Olive', '#4A6E3B', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-025', 'prod-shimmer', '025 | Orange', '#F25A1E', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-026', 'prod-shimmer', '026 | F-Rose', '#DE3D56', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-027', 'prod-shimmer', '027 | Half White', '#F8F5E4', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-028', 'prod-shimmer', '028 | D. Skin', '#B38354', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-029', 'prod-shimmer', '029 | D. Milange', '#54372D', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-030', 'prod-shimmer', '030 | Parrot', '#42C727', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-031', 'prod-shimmer', '031 | Jerry Red', '#D31434', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-032', 'prod-shimmer', '032 | L. Grey', '#82929E', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-033', 'prod-shimmer', '033 | Jute', '#B0A08D', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-034', 'prod-shimmer', '034 | D. Grey', '#47545D', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-035', 'prod-shimmer', '035 | Yellow', '#EDB91A', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-036', 'prod-shimmer', '036 | Stone', '#D6B495', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-037', 'prod-shimmer', '037 | Red Maroon', '#9B1D28', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-038', 'prod-shimmer', '038 | Royal Blue', '#194CB0', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-039', 'prod-shimmer', '039 | Grape', '#843E5E', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-040', 'prod-shimmer', '040 | Red Orange', '#E8291F', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-041', 'prod-shimmer', '041 | Pistar', '#1FB36C', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-042', 'prod-shimmer', '042 | Lrz Green', '#0D7B6C', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-043', 'prod-shimmer', '043 | Wine', '#672B3D', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-044', 'prod-shimmer', '044 | D. Pink', '#D9256E', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-045', 'prod-shimmer', '045 | Light Blue', '#95CCE5', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-046', 'prod-shimmer', '046 | Peach', '#EB7866', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-047', 'prod-shimmer', '047 | White', '#F3F4F6', '/products/shimmer-leggings.jpg'),
  ('prod-shimmer-c-048', 'prod-shimmer', '048 | Beige', '#DFD0BD', '/products/shimmer-leggings.jpg');
